# Model arguments
model_name_or_path: 
torch_dtype: null
# use_flash_attention_2: false

# Data training arguments
dataset_mixer:
  princeton-nlp/llama3-ultrafeedback: 0.01
dataset_splits:
- train
- test
preprocessing_num_workers: 12

# LoRA arguments
use_peft: true
load_in_4bit: true
lora_r: 16
lora_alpha: 16
lora_dropout: 0.05
lora_target_modules:
- q_proj
- k_proj
- v_proj
- o_proj

# CPOTrainer arguments
bf16: true
beta: 10
simpo_gamma: 5.4
cpo_alpha: 0.05
loss_type: simpo
do_eval: true
evaluation_strategy: steps
eval_steps: 400
gradient_accumulation_steps: 8
gradient_checkpointing: true
gradient_checkpointing_kwargs:
  use_reentrant: False
hub_model_id: cpo-simpo-exps
learning_rate: 1.0e-6
log_level: info
logging_steps: 5
lr_scheduler_type: cosine
max_length: 16384
max_prompt_length: 8192
num_train_epochs: 1
optim: adamw_torch
output_dir: 
run_name: llama-3-8b-instruct-cpo-simpo
per_device_train_batch_size: 1
per_device_eval_batch_size: 1
push_to_hub: false
save_strategy: "steps"
save_steps: 1000000
report_to:
- none
save_total_limit: 20
seed: 42
warmup_ratio: 0.1
